### ISSUE TITLE
Crash when starting up our app with torch_compat

### ISSUE THREAD

**Issue by vanlooverenkoen** [g123k/flutter_torch_compat#21]
This is the crash we get when starting up our app

```
Caused by java.util.NoSuchElementException: Array contains no element matching the predicate.
       at fr.g123k.torch_compat.impl.TorchCamera2Impl.<init>(TorchCamera2Impl.java:37)
       at fr.g123k.torch_compat.TorchCompatPlugin.<init>(TorchCompatPlugin.java:24)
       at fr.g123k.torch_compat.TorchCompatPlugin$Companion.registerWith(TorchCompatPlugin.java:39)
       at fr.g123k.torch_compat.TorchCompatPlugin.registerWith(TorchCompatPlugin.java:2)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:37)
       at be.our.app.MainActivity.configureFlutterEngine(MainActivity.java:19)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
       at be.our.app.MainActivity.onCreate(MainActivity.java:14)
       at android.app.Activity.performCreate(Activity.java:7876)
       at android.app.Activity.performCreate(Activity.java:7865)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3273)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by vanlooverenkoen** [comment]
`firstOrNull` should be used instead of `first`
Because for our app a flash is not required.
